Repository Taito-Code/Remote-Class, pull requests merged in 2021-12, with the labels that each got.

#12 Feature/custom cursor
  src/components/CursorIcon.tsx
  src/pages/index.tsx
  src/pages/signIn.tsx
  src/styles/CursorIcon.module.css
Labels: enhancement, good first issue, self-merged, UI/UX

#11 Feature: ログインページのスタイル変更
  package-lock.json
  package.json
  public/images/icon.png
  public/images/icon5_change.png
  public/images/login_img/loginbutton.png
  public/images/login_img/page1.png
  public/images/login_img/page2.png
  public/images/login_img/page3.png
  public/images/login_img/page4.png
  public/images/login_img/page5.png
  public/images/login_img/page6.png
  public/images/login_img/page7.png
  public/images/login_img/scroll.png
  public/images/login_img/underloginbutton.png
  src/components/IntroPage.tsx
  src/components/SignInHeader.tsx
  src/images/icon.png
  src/images/icon5_change.png
  src/images/login_img/login1.png
  src/images/login_img/login2.png
  src/images/login_img/login3.png
  src/images/login_img/login4.png
  src/images/login_img/login7.png
  src/images/login_img/loginbutton.png
  src/images/login_img/scroll.png
  src/images/login_img/under_login_button.png
  src/pages/signIn.tsx
  src/styles/IntroPage.module.css
  src/styles/SignInHeader.module.css
  src/styles/globals.css
  src/styles/scroll.module.css
  yarn.lock
Labels: enhancement, good first issue, UI/UX

#13 Update: indexページのデザインをいい感じにする
  package.json
  src/components/CursorIcon.tsx
  src/components/Header.tsx
  src/components/SignInHeader.tsx
  src/pages/index.tsx
  src/pages/signIn.tsx
  src/styles/CursorIcon.module.css
  src/styles/SignInHeader.module.css
  src/styles/globals.css
  yarn.lock
Labels: enhancement, self-merged, UI/UX
