Repository Taito-Code/Remote-Class, pull requests merged in 2022-01, with the labels that each got.

#18 基本的なチャット機能の追加
  src/components/BottomTextField.tsx
  src/components/Chat.tsx
  src/components/CursorIcon.tsx
  src/components/Fukidashi.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/fukidashi.module.css
  src/styles/textfield.module.css
Labels: enhancement, self-merged, UI/UX

#20 Feature: Slide機能の実装
  public/favicon.ico
  public/slide/slide1.png
  public/slide/slide2.png
  public/slide/slide3.png
  public/slide/slide4.png
  public/slide/slide5.png
  public/slide/slide6.png
  public/slide/slide7.png
  public/vercel.svg
  src/components/Slide.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
Labels: enhancement, self-merged, UI/UX

#21 fix chat css
  src/components/Chat.tsx
  src/pages/index.tsx
  src/styles/Chat.module.css
  src/styles/Home.module.css
  src/styles/fukidashi.module.css
Labels: bug, good first issue, UI/UX

#22 Fix: チャットのスタイルとアバターのスタイルを修正する
  src/components/CursorIcon.tsx
  src/components/Fukidashi.tsx
Labels: self-merged, UI/UX

#23 Fix: ログインの際のメールアドレスを限定する
  src/lib/login.ts
Labels: self-merged

#27 Fix:教室のHeaderアイコンの高さを調整する
  src/components/Header.tsx
Labels: bug, self-merged, UI/UX

#26 Feature: 着席機能を実装する
  src/components/Seat.tsx
  src/components/Table.tsx
  src/context/Seat.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/Seat.module.css
Labels: enhancement, self-merged, UI/UX, WIP

#30 Feature: 絵文字でのリアクション機能の実装
  src/components/EmojiExp.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
Labels: enhancement, self-merged, UI/UX

#32 Update: スライドを全体発表用のものに更新する
  public/slide/slide1.png
  public/slide/slide10.png
  public/slide/slide11.png
  public/slide/slide12.png
  public/slide/slide13.png
  public/slide/slide14.png
  public/slide/slide15.png
  public/slide/slide16.png
  public/slide/slide17.png
  public/slide/slide18.png
  public/slide/slide19.png
  public/slide/slide2.png
  public/slide/slide3.png
  public/slide/slide4.png
  public/slide/slide5.png
  public/slide/slide6.png
  public/slide/slide7.png
  public/slide/slide8.png
  public/slide/slide9.png
  src/components/Slide.tsx
Labels: self-merged
